### ISSUE TITLE
npm start leads to error, application produces directory listing

### ISSUE THREAD

**Issue by jasonthane** [shanebdavis/caffeine-script-demo#3]
> caffeine-script-demo@0.7.0 start /Users/jason/proj/caffeine-script-demo
> webpack-dev-server --hot --inline --progress

 10% [0] building modules 1/1 modules 0 active                                         
Project is running at http://localhost:8080/
webpack output is served from /
[0] Hash: 5300a3f52b8c4f228b31                                                            
Version: webpack 2.3.3
Child
    Hash: 5300a3f52b8c4f228b31
    Time: 1317ms
       Asset    Size  Chunks                    Chunk Names
    index.js  341 kB       0  [emitted]  [big]  index
    chunk    {0} index.js (index) 302 kB [entry] [rendered]
       [35] (webpack)/hot/emitter.js 77 bytes {0} [built]
       [36] ./index.caf 347 bytes {0} [built] [failed] [1 error]
       [37] (webpack)-dev-server/client?http://localhost:8080 5.44 kB {0} [built]
       [38] (webpack)/hot/dev-server.js 1.57 kB {0} [built]
       [39] ./~/ansi-html/index.js 4.26 kB {0} [built]
       [40] ./~/ansi-regex/index.js 135 bytes {0} [built]
       [42] ./~/events/events.js 8.33 kB {0} [built]
       [43] ./~/html-entities/index.js 231 bytes {0} [built]
       [50] ./~/querystring-es3/index.js 127 bytes {0} [built]
       [79] ./~/strip-ansi/index.js 161 bytes {0} [built]
       [81] ./~/url/url.js 23.3 kB {0} [built]
       [83] (webpack)-dev-server/client/overlay.js 3.6 kB {0} [built]
       [84] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
       [86] (webpack)/hot/log-apply-result.js 1.02 kB {0} [built]
       [87] multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index 52 bytes {0} [built]
         + 73 hidden modules
    
    ERROR in ./index.caf
    Module build failed: Error: A valid query string passed to parseQuery should begin with '?'
        at Object.parseQuery (/Users/jason/proj/caffeine-script-demo/node_modules/loader-utils/lib/parseQuery.js:13:9)
        at Object.module.exports (/Users/jason/proj/caffeine-script-demo/node_modules/caffeine-mc/webpack-loader.js:18:25)
     @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index

**Comment by jasonthane** [comment]
This is after the following steps:

git clone git@github.com:shanebdavis/caffeine-script-demo.git
cd caffeine-script-demo
npm install -g webpack
npm install art-build-configurator
npm start

**Comment by shanebdavis** [comment]
I suspect there may be a version issue with webpack. The failing line is a call into webpack's 'loader-utils'. Turns out, though, that call is just dead code and not needed, so I removed it from caffeine-mc (v1.19).

**Comment by shanebdavis** [comment]
Try this with a fresh install:
```
git clone git@github.com:shanebdavis/caffeine-script-demo.git
cd caffeine-script-demo/
npm install
node_modules/.bin/webpack-dev-server
```

Then go here: http://localhost:8080/index

**Comment by jasonthane** [comment]
Fresh install successful; closing the issue.
